# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(max_length=280)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('priority', models.IntegerField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='Baja')),
                ('has_alarm', models.BooleanField(default=False)),
                ('due_date', models.DateTimeField()),
                ('completed', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('father_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nota_padre', to='notes.Note')),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_time', models.DateTimeField()),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.Note')),
            ],
        ),
    ]
