# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 02:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='father_note',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_padre', to='notes.Note'),
        ),
        migrations.AlterField(
            model_name='note',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('1', 'Alta'), ('2', 'Media'), ('3', 'Baja')], default='Baja', max_length=5),
        ),
    ]
