# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-11-12 02:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20161112_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='father_note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='nota_padre', to='notes.Note'),
        ),
    ]
